image: docker:latest

stages:
  - build
  - deploy

variables:
  COMMIT_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  DEPLOY_USER: $CI_DEPLOY_USER
  DEPLOY_SERVER_PROD: $CI_DEPLOY_SERVER_PROD
  DEPLOY_SERVER_DEV: $CI_DEPLOY_SERVER_DEV
  DEPLOY_DIR_PROD: /deployments/leochat
  DEPLOY_DIR_DEV: /development/leochat_dev
  LEONINE_REGISTRY: registry.leoninestudios.com
  DEPLOY_TOKEN_USER_METRICS: $DEPLOY_TOKEN_USER_METRICS
  DEPLOY_TOKEN_PASSWORD_METRICSD: $DEPLOY_TOKEN_PASSWORD_METRICS
  # CI_VERBOSE: "true"

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  - echo $DEPLOY_TOKEN_PASSWORD_METRICS | docker login -u $DEPLOY_TOKEN_USER_METRICS --password-stdin $LEONINE_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG -f Dockerfile . # wrote debug statement to trigger new build
    # - docker tag $IMAGE_TAG $LATEST_TAG
    - docker tag $IMAGE_TAG $COMMIT_TAG
    - docker push $IMAGE_TAG
    # - docker push $LATEST_TAG
    - docker push $COMMIT_TAG
  tags:
    - runner-01
  only:
    - tags
    - main
    # - develop # added comment for commit 
    
deploy-prod:
  stage: deploy
  tags: 
    - runner-01
  only:
    - main
    - tags
    
  script:
    # Pre-deploy steps
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p 35039 $DEPLOY_SERVER_PROD >> ~/.ssh/known_hosts

    # # Export commit tag
    - export COMMIT_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    
    # Deploy steps
    - scp -P 35039 -o StrictHostKeyChecking=no docker-compose.yml $DEPLOY_USER@$DEPLOY_SERVER_PROD:$DEPLOY_DIR_PROD/docker-compose.yml
    - scp -P 35039 -o StrictHostKeyChecking=no docker-compose.prod.yml $DEPLOY_USER@$DEPLOY_SERVER_PROD:$DEPLOY_DIR_PROD/docker-compose.prod.yml
    - scp -P 35039 -o StrictHostKeyChecking=no launch.sh $DEPLOY_USER@$DEPLOY_SERVER_PROD:$DEPLOY_DIR_PROD/launch.sh
    - |
      ssh -p 35039 $DEPLOY_USER@$DEPLOY_SERVER_PROD \
      "export COMMIT_TAG=$COMMIT_TAG && \
      echo \"$CI_REGISTRY_PASSWORD\" | docker login -u \"$CI_REGISTRY_USER\" --password-stdin $CI_REGISTRY && \
      cd $DEPLOY_DIR_PROD && \
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d"

deploy-dev:
  stage: deploy
  tags: 
    - runner-01
  only:
    - develop
    
  script:
    # Pre-deploy steps
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p 35039 $DEPLOY_SERVER_DEV >> ~/.ssh/known_hosts

    # # Export commit tag
    - export COMMIT_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    
    # # Deploy steps
    - scp -P 35039 -o StrictHostKeyChecking=no docker-compose.yml $DEPLOY_USER@$DEPLOY_SERVER_DEV:$DEPLOY_DIR_DEV/docker-compose.yml
    - scp -P 35039 -o StrictHostKeyChecking=no docker-compose.dev.yml $DEPLOY_USER@$DEPLOY_SERVER_DEV:$DEPLOY_DIR_DEV/docker-compose.dev.yml
    - |
      ssh -p 35039 -o StrictHostKeyChecking=no \
          $DEPLOY_USER@$DEPLOY_SERVER_DEV \
          "export COMMIT_TAG=$COMMIT_TAG && \
          echo \"$CI_REGISTRY_PASSWORD\" | docker login -u \"$CI_REGISTRY_USER\" --password-stdin \"$CI_REGISTRY\" && \
          cd \"$DEPLOY_DIR_DEV\" && \
          docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d"

