image: docker:latest

stages:
  - build
  - deploy

variables:
  COMMIT_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  DEPLOY_USER: $CI_DEPLOY_USER
  DEPLOY_SERVER_PROD: $CI_DEPLOY_SERVER_PROD
  DEPLOY_SERVER_DEV: $CI_DEPLOY_SERVER_DEV
  DEPLOY_DIR_PROD: /deployments/leochat
  DEPLOY_DIR_DEV: /development/leochat
  CI_VERBOSE: "true"

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG -f Dockerfile .
    # - docker tag $IMAGE_TAG $LATEST_TAG
    - docker tag $IMAGE_TAG $COMMIT_TAG
    - docker push $IMAGE_TAG
    # - docker push $LATEST_TAG
    - docker push $COMMIT_TAG
  tags:
    - runner-01
  only:
    - tags
    - main
    
deploy-prod:
  stage: deploy
  tags: 
    - runner-01
  only:
    - tags
    
  script:
    # Pre-deploy steps
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p 35039 $DEPLOY_SERVER_PROD >> ~/.ssh/known_hosts
    
    # Deploy steps
    - scp -P 35039 -o StrictHostKeyChecking=no docker-compose.yml $DEPLOY_USER@$DEPLOY_SERVER_PROD:$DEPLOY_DIR_PROD/docker-compose.yml
    - scp -P 35039 -o StrictHostKeyChecking=no docker-compose.prod.yml $DEPLOY_USER@$DEPLOY_SERVER_PROD:$DEPLOY_DIR_PROD/docker-compose.prod.yml
    - scp -P 35039 -o StrictHostKeyChecking=no launch.sh $DEPLOY_USER@$DEPLOY_SERVER_PROD:$DEPLOY_DIR_PROD/launch.sh
    - ssh -p 35039 $DEPLOY_USER@$DEPLOY_SERVER_PROD "
        echo \"$CI_REGISTRY_PASSWORD\" | docker login -u \"$CI_REGISTRY_USER\" --password-stdin $CI_REGISTRY &&
        cd $DEPLOY_DIR_PROD && bash launch.sh
      "

deploy-dev:
  stage: deploy
  tags: 
    - runner-01
  only:
    - main
    
  script:
    # Pre-deploy steps
    - set -x
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ping $DEPLOY_SERVER_DEV
    # - ssh-keyscan -p 35039 $DEPLOY_SERVER_DEV >> ~/.ssh/known_hosts

    # # Export commit tag
    # - export COMMIT_TAG=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    
    # # Deploy steps
    # - scp -P 35039 -o StrictHostKeyChecking=no docker-compose.yml $DEPLOY_USER@$DEPLOY_SERVER_DEV:$DEPLOY_DIR_DEV/docker-compose.yml
    # - scp -P 35039 -o StrictHostKeyChecking=no docker-compose.dev.yml $DEPLOY_USER@$DEPLOY_SERVER_DEV:$DEPLOY_DIR_DEV/docker-compose.dev.yml
    # - ssh -p 35039 $DEPLOY_USER@$DEPLOY_SERVER_DEV "
    #     echo \"$CI_REGISTRY_PASSWORD\" | docker login -u \"$CI_REGISTRY_USER\" --password-stdin $CI_REGISTRY &&
    #     cd $DEPLOY_DIR_DEV && docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d
    #   "
