global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: librechat
   static_configs:
    - targets:
        - 'metrics:8000'