version: "3.8"

services:
  mongodb:
    container_name: mongodb-dev
    expose:
      - 27017
    ports:
      - 27017:27017
    image: mongo
    # restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: meilisearch-dev
    image: getmeili/meilisearch:v1.5
    # restart: always
    expose:
      - 7700
    # Uncomment this to access meilisearch from outside docker
    ports: 
      - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=5c71cf56d672d009e36070b5bc5e47b743535ae55c818ae3b735bb6ebfb4ba63
    volumes:
      - ./meili_data_v1.5:/meili_data
